import forum from 'assets/forum.png';

export const forumCategories = [
  {
    id: '1',
    name: 'Туризм',
    link: '/tourism',
    section: 'Tourism',
    color: '#F84A00',
  },
  {
    id: '2',
    name: 'Недвижимость',
    link: '/realty',
    section: 'Real Estate',
    color: '#6B6B6B',
  },
  {
    id: '3',
    name: 'Спорт',
    link: '/sport',
    section: 'Sport',
    color: '#278AFF',
  },
  {
    id: '4',
    name: 'Охота',
    link: '/hunting',
    section: 'Hunting',
    color: '#F4911C',
  },
  {
    id: '5',
    name: 'Ремонт',
    link: '/repairing',
    section: 'Repairing',
    color: '#8D6969',
  },
  {
    id: '6',
    name: 'Игры',
    link: '/games',
    section: 'Games',
    color: '#5E24A9',
  },
  {
    id: '7',
    name: 'Рыбалка',
    link: '/fishing',
    section: 'Fishing',
    color: '#807DFF',
  },
  {
    id: '8',
    name: 'Компьютеры, электоника, техника',
    link: '/electronics',
    section: 'Electronics',
    color: '#735167',
  },
  {
    id: '9',
    name: 'Здоровье, красота',
    link: '/beauty',
    section: 'Health and beauty',
    color: '#CA06AB',
  },
  {
    id: '10',
    name: 'Путешествия',
    link: '/travelling',
    section: 'Travelling',
    color: '#C253D4',
  },
  {
    id: '11',
    name: 'Справки, документы',
    link: '/documents',
    section: 'Documents',
    color: '#66658E',
  },
  {
    id: '12',
    name: 'Для родителей',
    link: '/forParents',
    section: 'For parents',
    color: '#EF6666',
  },
  {
    id: '13',
    name: 'Всё о городе',
    link: '/city',
    section: 'All about city',
    color: '#C03232',
  },
  {
    id: '14',
    name: 'Авто',
    link: '/auto',
    section: 'Auto',
    color: '#56746F',
  },
  {
    id: '15',
    name: 'Домашние животные',
    link: '/animals',
    section: 'Animals',
    color: '#F41C5D',
  },
  {
    id: '16',
    name: 'Кулинария',
    link: '/cooking',
    section: 'Cooking',
    color: '#5B8B1D',
  },
  {
    id: '17',
    name: 'Растения',
    link: '/plants',
    section: 'Plants',
    color: '#61714C',
  },
  {
    id: '18',
    name: 'Другое',
    link: '/other',
    section: 'Other',
    color: '#485D5F',
  },
  {
    id: '19',
    name: 'Форум',
    img: forum,
    link: '/forum',
    hideSearch: true,
  },
  {
    id: '20',
    name: 'Создать тему',
    link: '/createTheme',
    hideSearch: true,
  },
  {
    id: '21',
    name: 'Обсуждения',
    link: '/theme',
    hideSearch: true,
  },
];
