import img from 'assets/test/Rectangle 48.png';
import img2 from 'assets/test/Rectangle 49.png';
import img3 from 'assets/test/Rectangle 50.png';
import img4 from 'assets/test/Rectangle 51.png';
import photo from 'assets/test/Frame 223.png';
import photo2 from 'assets/test/3d_avatar_7.png';
import photo3 from 'assets/test/3d_avatar_8.png';
import photo4 from 'assets/test/3d_avatar_9.png';
import photo5 from 'assets/test/3d_avatar_10.png';
import car1 from 'assets/test/car1.png';
import car2 from 'assets/test/car2.png';
import car3 from 'assets/test/car3.png';
import car4 from 'assets/test/car4.png';
import car5 from 'assets/test/car5.png';
import car6 from 'assets/test/car6.png';
import moto from 'assets/test/moto.png';
import moto2 from 'assets/test/moto2.png';
import moto3 from 'assets/test/moto3.png';
import mop from 'assets/test/mop.png';
import cat from 'assets/test/cat.png';
import cat2 from 'assets/test/cat2.png';
import dog from 'assets/test/dog.png';
import dog2 from 'assets/test/dog2.png';
import bird from 'assets/test/parrot.png';
import other from 'assets/test/other.png';
import other2 from 'assets/test/other2.png';
import relax from 'assets/test/relax.png';
import relax2 from 'assets/test/relax2.png';
import velo from 'assets/test/velo.png';
import velo2 from 'assets/test/velo2.png';
import sport from 'assets/test/sport.png';
import sport2 from 'assets/test/sport2.png';
import sport3 from 'assets/test/sport3.png';
import hunting from 'assets/test/hunting.png';
import clothes from 'assets/test/clothes.png';
import clothes2 from 'assets/test/clothes2.png';
import clothes3 from 'assets/test/clothes3.png';
import clothes4 from 'assets/test/clothes4.png';
import clothes5 from 'assets/test/clothes5.png';
import clothes6 from 'assets/test/clothes6.png';
import clothes7 from 'assets/test/clothes7.png';

export const testMain = [
  {
    advertId: '1',
    title: 'Mitsubishi Lancer 1.6 MT, 2004, 257 888 км',
    files: [img],
    dateOfCreation: '2023-07-21T15:00:57.599',
  },
  {
    advertId: '2',
    title: 'Сумочка женская, Giorgio Armani, 2022',
    files: [img2],
    dateOfCreation: '2023-07-21T15:00:57.599',
  },
  {
    advertId: '3',
    title: 'Котята',
    files: [img3],
    dateOfCreation: '2023-07-21T15:00:57.599',
  },
  {
    advertId: '4',
    title: 'Табурет для дома и дачи',
    files: [img4],
    dateOfCreation: '2023-07-21T15:00:57.599',
  },
];

export const serverResponses = [
  {
    advertId: '1',
    title: 'Mitsubishi Lancer 1.6 MT, 2004, 257 888 км',
    description:
      'Кузов без дыр и ржавчины.Новая резина .Всё работает,крутится и светит.Ручник держит.Вин читается отлично.Не прихотливый авто.Чистый салон.Есть действующий ТехОсмотр.Отличное состояние.перекупов и из салонов не беспокоить.Продам сам.',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Transport',
    subsection: 'Autos',
    price: '8000 USD',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [
      {
        nickName: 'Никита',
        userName: 'Nikwithnickname',
        userPhoto: photo2,
        text: 'Хорошая машина, но мне кажется не за свою цену',
        comments: [
          {
            nickName: 'Анна',
            userName: 'Annwithnickname',
            userPhoto: photo3,
            text: 'Хорошая машина, но мне кажется не за свою цену',
          },
        ],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'О, у меня была такая же! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Машина комфортная, советую, но у меня нет денег...',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'О, у меня была такая же! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Машина комфортная, советую, но у меня нет денег...',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'О, у меня была такая же! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Машина комфортная, советую, но у меня нет денег...',
        comments: [],
      },
    ],
    files: [img, car1, car2, car3],
  },
  {
    advertId: '2',
    title: 'Сумочка женская, Giorgio Armani, 2022',
    description: 'описание',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Clothes and personal things',
    subsection: 'Clothing, shoes, accessories',
    price: '50 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [
      {
        nickName: 'Никита',
        userName: 'Nikwithnickname',
        userPhoto: photo2,
        text: 'Хорошая сумочка, у жены такая же',
        comments: [
          {
            nickName: 'Анна',
            userName: 'Annwithnickname',
            userPhoto: photo3,
            text: 'Хорошая , но мне кажется не за свою цену',
          },
        ],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Подарил девушке такую! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Сумка удобная, советую, но у меня нет денег...',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Куплю в подарок',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Торг уместен?',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Что на счет торга?',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Ждем ответа',
        comments: [],
      },
    ],
    files: [img2],
  },
  {
    advertId: '3',
    title: 'Котята',
    description: 'описание',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Animals',
    subsection: 'Cats',
    price: '90 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [
      {
        nickName: 'Никита',
        userName: 'Nikwithnickname',
        userPhoto: photo2,
        text: 'Какие милые',
        comments: [
          {
            nickName: 'Анна',
            userName: 'Annwithnickname',
            userPhoto: photo3,
            text: 'Согласна хорошенькие',
          },
        ],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Подарил девушке такую! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Классные',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Куплю в подарок',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Торг уместен?',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Что на счет торга?',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Ждем ответа',
        comments: [],
      },
    ],
    files: [img3],
  },

  {
    advertId: '4',
    title: 'Табурет для дома и дачи',
    description: 'описание',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'House and garden',
    price: '90 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [
      {
        nickName: 'Никита',
        userName: 'Nikwithnickname',
        userPhoto: photo2,
        text: 'Удобный и надежный',
        comments: [
          {
            nickName: 'Анна',
            userName: 'Annwithnickname',
            userPhoto: photo3,
            text: 'Согласна мне нравится',
          },
        ],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Возьмуу на дачу',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Классный',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Куплю в подарок',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Торг уместен?',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Что на счет торга?',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Ждем ответа',
        comments: [],
      },
    ],
    files: [img4],
  },
  {
    advertId: '5',
    title: 'Chery Tiggo 8 Pro Max 2.0 AMT, 2023',
    description: 'Долгое время не использовался, взял авто для работы. Недорого',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Transport',
    subsection: 'Autos',
    price: '6 020,29 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [
      {
        nickName: 'Никита',
        userName: 'Nikwithnickname',
        userPhoto: photo2,
        text: 'Хорошая машина, но мне кажется не за свою цену',
        comments: [
          {
            nickName: 'Анна',
            userName: 'Annwithnickname',
            userPhoto: photo3,
            text: 'Хорошая машина, но мне кажется не за свою цену',
          },
        ],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'О, у меня была такая же! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Машина комфортная, советую, но у меня нет денег...',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'О, у меня была такая же! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Машина комфортная, советую, но у меня нет денег...',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'О, у меня была такая же! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Машина комфортная, советую, но у меня нет денег...',
        comments: [],
      },
    ],
    files: [car4],
  },
  {
    advertId: '6',
    title: 'Toyota Fortuner Legender exterior',
    description: 'Машина в хорошем состоянии. Жидкости меняли по регламенту. Сел и поехал.Торг присутствует...',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Transport',
    subsection: 'Autos',
    price: '10 000,00 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [
      {
        nickName: 'Никита',
        userName: 'Nikwithnickname',
        userPhoto: photo2,
        text: 'Хорошая машина, но мне кажется не за свою цену',
        comments: [
          {
            nickName: 'Анна',
            userName: 'Annwithnickname',
            userPhoto: photo3,
            text: 'Хорошая машина, но мне кажется не за свою цену',
          },
        ],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'О, у меня была такая же! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Машина комфортная, советую, но у меня нет денег...',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'О, у меня была такая же! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Машина комфортная, советую, но у меня нет денег...',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'О, у меня была такая же! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Машина комфортная, советую, но у меня нет денег...',
        comments: [],
      },
    ],
    files: [car5],
  },
  {
    advertId: '7',
    title: 'Honda XR-V 1.5 CVT, 2023',
    description: 'Хороший внешний вид. Двигатель работает идеально. Вся электрика работает.',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Transport',
    subsection: 'Autos',
    price: '5 300,99 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [
      {
        nickName: 'Никита',
        userName: 'Nikwithnickname',
        userPhoto: photo2,
        text: 'Хорошая машина, но мне кажется не за свою цену',
        comments: [
          {
            nickName: 'Анна',
            userName: 'Annwithnickname',
            userPhoto: photo3,
            text: 'Хорошая машина, но мне кажется не за свою цену',
          },
        ],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'О, у меня была такая же! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Машина комфортная, советую, но у меня нет денег...',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'О, у меня была такая же! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Машина комфортная, советую, но у меня нет денег...',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'О, у меня была такая же! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Машина комфортная, советую, но у меня нет денег...',
        comments: [],
      },
    ],
    files: [car6],
  },
  {
    advertId: '8',
    title: 'Днепр 10-36',
    description: 'Покупал 3 года назад. Хороший мотоцикл ',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Transport',
    subsection: 'MotorBikes',
    price: '8 095,29 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [
      {
        nickName: 'Никита',
        userName: 'Nikwithnickname',
        userPhoto: photo2,
        text: 'Хороший мотоцикл, но мне кажется не за свою цену',
        comments: [
          {
            nickName: 'Анна',
            userName: 'Annwithnickname',
            userPhoto: photo3,
            text: 'Согласна',
          },
        ],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'О, у меня был такой же! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: ' советую',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Торг уместен?',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Крутой...',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Что на счет торга?',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Ждем ответ',
        comments: [],
      },
    ],
    files: [moto],
  },
  {
    advertId: '9',
    title: 'Мопед ZIP Motors Alpha LUX',
    description: 'Покупал 3 года назад. Хороший мопед ',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Transport',
    subsection: 'MotorBikes',
    price: '8 095,29 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [
      {
        nickName: 'Никита',
        userName: 'Nikwithnickname',
        userPhoto: photo2,
        text: 'Хороший мотоцикл, но мне кажется не за свою цену',
        comments: [
          {
            nickName: 'Анна',
            userName: 'Annwithnickname',
            userPhoto: photo3,
            text: 'Согласна',
          },
        ],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'О, у меня был такой же! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: ' советую',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Торг уместен?',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Крутой...',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Что на счет торга?',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Ждем ответ',
        comments: [],
      },
    ],
    files: [mop],
  },
  {
    advertId: '10',
    title: 'Bike reviews for Ski-Doo Tundra',
    description: 'Покупал 3 года назад. Хороший снегоход  ',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Transport',
    subsection: 'Quadbikes, snowbikes and water transport',
    price: '8 095,29 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [
      {
        nickName: 'Никита',
        userName: 'Nikwithnickname',
        userPhoto: photo2,
        text: 'Хороший мотоцикл, но мне кажется не за свою цену',
        comments: [
          {
            nickName: 'Анна',
            userName: 'Annwithnickname',
            userPhoto: photo3,
            text: 'Согласна',
          },
        ],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'О, у меня был такой же! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: ' советую',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Торг уместен?',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Крутой...',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Что на счет торга?',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Ждем ответ',
        comments: [],
      },
    ],
    files: [moto2],
  },
  {
    advertId: '11',
    title: 'CFMOTO CFORCE 500 HO',
    description: 'Квадрацикл в хорошем состоянии. Жидкости меняли по регламенту. Сел и поехал.Торг присутствует...',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Transport',
    subsection: 'Quadbikes, snowbikes and water transport',
    price: '8 095,29 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [
      {
        nickName: 'Никита',
        userName: 'Nikwithnickname',
        userPhoto: photo2,
        text: 'Хороший мотоцикл, но мне кажется не за свою цену',
        comments: [
          {
            nickName: 'Анна',
            userName: 'Annwithnickname',
            userPhoto: photo3,
            text: 'Согласна',
          },
        ],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'О, у меня был такой же! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: ' советую',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Торг уместен?',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Крутой...',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Что на счет торга?',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Ждем ответ',
        comments: [],
      },
    ],
    files: [moto3],
  },
  {
    advertId: '12',
    title: 'Маленький котенок',
    description: 'Нашли на улице, не стали бросать',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Animals',
    subsection: 'Cats',
    price: 'Бесплатно',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [
      {
        nickName: 'Никита',
        userName: 'Nikwithnickname',
        userPhoto: photo2,
        text: 'Классный кот',
        comments: [
          {
            nickName: 'Анна',
            userName: 'Annwithnickname',
            userPhoto: photo3,
            text: 'Согласна супер',
          },
        ],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Подарил девушке такого! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Классные',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Куплю в подарок',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Привитый?',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'К лотку приучен?',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Ждем ответа',
        comments: [],
      },
    ],
    files: [cat],
  },
  {
    advertId: '13',
    title: 'Шотландский кот',
    description: 'Породистый кот. Имеет паспорт',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Animals',
    subsection: 'Cats',
    price: '100,29 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [
      {
        nickName: 'Никита',
        userName: 'Nikwithnickname',
        userPhoto: photo2,
        text: 'Классный кот',
        comments: [
          {
            nickName: 'Анна',
            userName: 'Annwithnickname',
            userPhoto: photo3,
            text: 'Согласна супер',
          },
        ],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Подарил девушке такого! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Классные',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Куплю в подарок',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Привитый?',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'К лотку приучен?',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Ждем ответа',
        comments: [],
      },
    ],
    files: [cat2],
  },
  {
    advertId: '14',
    title: 'Маленькие мопсики',
    description: 'Щенкам 2 месяца. Привиты, кастрированы и стерилизованы',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Animals',
    subsection: 'Dogs',
    price: '350,00 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [
      {
        nickName: 'Никита',
        userName: 'Nikwithnickname',
        userPhoto: photo2,
        text: 'Классные собаки',
        comments: [
          {
            nickName: 'Анна',
            userName: 'Annwithnickname',
            userPhoto: photo3,
            text: 'Согласна супер',
          },
        ],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Подарил девушке такого! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Классные',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Куплю в подарок',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Привитые?',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Привередливы в питании?',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Ждем ответа',
        comments: [],
      },
    ],
    files: [dog],
  },
  {
    advertId: '156',
    title: 'Полностью ручные попугайчики',
    description: 'Корелла , неразлучник, розелла , и все что нужно для их содержания',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Animals',
    subsection: 'Birds',
    price: 'Договорная',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [
      {
        nickName: 'Никита',
        userName: 'Nikwithnickname',
        userPhoto: photo2,
        text: 'Классные птички',
        comments: [
          {
            nickName: 'Анна',
            userName: 'Annwithnickname',
            userPhoto: photo3,
            text: 'Согласна супер',
          },
        ],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Подарил девушке такого! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Классные',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Куплю в подарок',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Привередливы в питании?',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Ждем ответа',
        comments: [],
      },
    ],
    files: [bird],
  },
  {
    advertId: '155',
    title: 'Свинка мини пиг',
    description:
      'Продам минипига. Только ответственным людям. Пиг самец, возраст год и 1 месяц. Весит 9 кг. Самец, не кастрирован. Может жить и в квартире и в частном доме.',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Animals',
    subsection: 'Other',
    price: '100 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [
      {
        nickName: 'Никита',
        userName: 'Nikwithnickname',
        userPhoto: photo2,
        text: 'Классные свинки',
        comments: [
          {
            nickName: 'Анна',
            userName: 'Annwithnickname',
            userPhoto: photo3,
            text: 'Согласна супер',
          },
        ],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Подарил девушке такого! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Классные',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Куплю в подарок',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Привередливы в питании?',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Ждем ответа',
        comments: [],
      },
    ],
    files: [other2],
  },
  {
    advertId: '16',
    title: 'Вельш корги мини',
    description:
      'Очаровательный мальчик вельш корги пемброк рыже-белого окраса предлагается к продаже. Привит по возрасту, приучен к корму и пеленочке, очень ласковый и общительный. Дополнительная информация по телефону. doska.by',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Animals',
    subsection: 'Dogs',
    price: '500 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [
      {
        nickName: 'Никита',
        userName: 'Nikwithnickname',
        userPhoto: photo2,
        text: 'Классные собаки',
        comments: [
          {
            nickName: 'Анна',
            userName: 'Annwithnickname',
            userPhoto: photo3,
            text: 'Согласна супер',
          },
        ],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Подарил девушке такого! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Классные',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Куплю в подарок',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Привитые?',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Привередливы в питании?',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Ждем ответа',
        comments: [],
      },
    ],
    files: [dog2],
  },
  {
    advertId: '15',
    title: 'Свинка мини пиг',
    description:
      'Продам минипига. Только ответственным людям. Пиг самец, возраст год и 1 месяц. Весит 9 кг. Самец, не кастрирован. Может жить и в квартире и в частном доме.',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Animals',
    subsection: 'Other',
    price: '100 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [
      {
        nickName: 'Никита',
        userName: 'Nikwithnickname',
        userPhoto: photo2,
        text: 'Классные свинки',
        comments: [
          {
            nickName: 'Анна',
            userName: 'Annwithnickname',
            userPhoto: photo3,
            text: 'Согласна супер',
          },
        ],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Подарил девушке такого! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Классные',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Куплю в подарок',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Привередливы в питании?',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Ждем ответа',
        comments: [],
      },
    ],
    files: [other],
  },
  {
    advertId: '16',
    title: 'Коптильня',
    description: 'Хороший аппарат',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Sports and relax',
    subsection: 'Tourism',
    price: '100 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [
      {
        nickName: 'Никита',
        userName: 'Nikwithnickname',
        userPhoto: photo2,
        text: 'Классный аппарат',
        comments: [
          {
            nickName: 'Анна',
            userName: 'Annwithnickname',
            userPhoto: photo3,
            text: 'Согласна супер',
          },
        ],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Купил такой! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Классный',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Куплю в подарок',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Торг уместен?',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Ждем ответа',
        comments: [],
      },
    ],
    files: [relax],
  },
  {
    advertId: '17',
    title: 'Велосипед',
    description: '5 лет ездил. Решил что стоит продать',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Sports and relax',
    subsection: 'Bicycles and accessories',
    price: '100,29 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [],
    files: [velo],
  },
  {
    advertId: '18',
    title: 'Новый велосипед',
    description: 'Хороший велик. Год гарантии. Все чеки сохранены',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Sports and relax',
    subsection: 'Bicycles and accessories',
    price: '350,00 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [
      {
        nickName: 'Никита',
        userName: 'Nikwithnickname',
        userPhoto: photo2,
        text: 'Классный аппарат',
        comments: [
          {
            nickName: 'Анна',
            userName: 'Annwithnickname',
            userPhoto: photo3,
            text: 'Согласна супер',
          },
        ],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Купил такой! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Классный',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Куплю в подарок',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Торг уместен?',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Ждем ответа',
        comments: [],
      },
    ],
    files: [velo2],
  },
  {
    advertId: '19',
    title: 'Ролики',
    description: 'Ролики для девочек, Серо-белого цвета. Очень удобные, почти новые',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Sports and relax',
    subsection: 'Sport',
    price: '120,99 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [],
    files: [sport],
  },
  {
    advertId: '20',
    title: 'Гамак',
    description: 'Гамак ручной работы.изготовлю.',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Sports and relax',
    subsection: 'Tourism',
    price: '229 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [
      {
        nickName: 'Никита',
        userName: 'Nikwithnickname',
        userPhoto: photo2,
        text: 'Классный',
        comments: [
          {
            nickName: 'Анна',
            userName: 'Annwithnickname',
            userPhoto: photo3,
            text: 'Согласна супер',
          },
        ],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Купил такой! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Классный',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Куплю в подарок',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Торг уместен?',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Ждем ответа',
        comments: [],
      },
    ],
    files: [relax2],
  },
  {
    advertId: '21',
    title: 'Cпиннинг для рыбалки',
    description: 'Новый',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Sports and relax',
    subsection: 'Hunting and fishing',
    price: '100 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [
      {
        nickName: 'Никита',
        userName: 'Nikwithnickname',
        userPhoto: photo2,
        text: 'Классный',
        comments: [
          {
            nickName: 'Анна',
            userName: 'Annwithnickname',
            userPhoto: photo3,
            text: 'Согласна супер',
          },
        ],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Купил такой! Топчик',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Классный',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Куплю в подарок',
        comments: [],
      },
      {
        nickName: 'Константин',
        userName: 'Koswithnickname',
        userPhoto: photo4,
        text: 'Торг уместен?',
        comments: [],
      },
      {
        nickName: 'Анна',
        userName: 'Annwithnickname',
        userPhoto: photo5,
        text: 'Ждем ответа',
        comments: [],
      },
    ],
    files: [hunting],
  },
  {
    advertId: '22',
    title: 'Баскетбольный мяч',
    description: 'Новый',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Sports and relax',
    subsection: 'Sport',
    price: '30 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [],
    files: [sport2],
  },
  {
    advertId: '23',
    title: 'Скейтборд',
    description: 'Новый',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Sports and relax',
    subsection: 'Sport',
    price: '40 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [],
    files: [sport3],
  },
  {
    advertId: '24',
    title: 'Женский топ',
    description: 'Новый топик',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Clothes and personal things',
    subsection: 'Clothing, shoes, accessories',
    price: '30,29 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [],
    files: [clothes],
  },
  {
    advertId: '25',
    title: 'Солнечные очки',
    description: 'Солнечные очки для настоящих модниц',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Clothes and personal things',
    subsection: 'Clothing, shoes, accessories',
    price: '30,29 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [],
    files: [clothes2],
  },
  {
    advertId: '26',
    title: 'Серьги',
    description: 'Золотой цвет. Бижутерия. Покупались год назад',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Clothes and personal things',
    subsection: 'Clothing, shoes, accessories',
    price: '10,00 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [],
    files: [clothes3],
  },
  {
    advertId: '27',
    title: 'Крем для лица',
    description: 'Хороший крем, новая упаковка. Не подошел',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Clothes and personal things',
    subsection: 'Beauty and health',
    price: '10,00 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [],
    files: [clothes4],
  },
  {
    advertId: '28',
    title: 'Туфли мужские',
    description: 'Новые',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Clothes and personal things',
    subsection: 'Clothing, shoes, accessories',
    price: '150,00 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [],
    files: [clothes5],
  },
  {
    advertId: '29',
    title: 'Мужской парфюм',
    description: 'Новый, не подошел',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Clothes and personal things',
    subsection: 'Beauty and health',
    price: '95,00 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [],
    files: [clothes6],
  },
  {
    advertId: '30',
    title: 'Солнечные очки',
    description: 'Солнечные очки для мужчин',
    nickName: 'Андрей',
    userName: 'Andrushasmely',
    userPhoto: photo,
    section: 'Clothes and personal things',
    subsection: 'Clothing, shoes, accessories',
    price: '50,29 BYN',
    dateOfCreation: '2023-07-21T15:00:57.599',
    comments: [],
    files: [clothes7],
  },
];
